### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int' when converting to liger object

### ISSUE THREAD

**Issue by mumichae** [welch-lab/pyliger#12]
When I try to convert a list of anndatas to a liger object, I get the following error.

```
Traceback (most recent call last):
  File "/tmp/viash-run-pyliger-RJKJdN.py", line 68, in <module>
    lobj = pyliger.create_liger([adata])
  File "/usr/local/lib/python3.10/site-packages/pyliger/preprocessing/_initialization.py", line 68, in create_liger
    liger_object = _create_liger_matrix(adata_list, make_sparse, take_gene_union, remove_missing)
  File "/usr/local/lib/python3.10/site-packages/pyliger/preprocessing/_initialization.py", line 125, in _create_liger_matrix
    adata_list[idx].X = csr_matrix(adata_list[idx].X, dtype=np.int)
  File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

**Comment by theAeon** [comment]
I'll patch that-in the meantime downgrade numpy to the 1.23 series.

Thanks for catching that.

**Comment by theAeon** [comment]
Should be set. Realized I forgot to promote 0.2.0 to release, so I included this patch when bumping it.
